let DB=null,watchId=null,tripStarted=null,lastPos=null,tripMeters=0,tripSpeeds=[],installPrompt=null;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const fmt=(n,d=0)=>n==null?'—':Number(n).toLocaleString('fr-FR',{minimumFractionDigits:d,maximumFractionDigits:d});
const euro=n=>n==null?'—':Number(n).toLocaleString('fr-FR',{style:'currency',currency:'EUR'});
const dateFR=s=>s?new Date(s).toLocaleDateString('fr-FR'):'—';
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2600)}
function show(id){$$('.view').forEach(x=>x.classList.toggle('active',x.id===id));$$('.bottom button').forEach(x=>x.classList.toggle('selected',x.dataset.go===id));scrollTo(0,0)}
$$('[data-go]').forEach(b=>b.onclick=()=>show(b.dataset.go));$$('.back').forEach(b=>b.onclick=()=>show('home'));
function tick(){const d=new Date();$('#clock').textContent=d.toLocaleDateString('fr-FR',{weekday:'long',day:'numeric',month:'long'})+' • '+d.toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'})}tick();setInterval(tick,1000);
async function load(){DB=await fetch('data/fiesta-data.json').then(r=>r.json());render()}
function render(){const s=DB.summary,v=DB.vehicle;$('#vehicleLine').textContent=`${v.name} • ${fmt(s.currentOdometer)} km`;$('#odo').textContent=fmt(s.currentOdometer)+' km';$('#avg').textContent=fmt(s.averageConsumption,1)+' L/100';$('#fuelSpend').textContent=euro(s.fuelSpend);$('#vOdo').textContent=fmt(s.currentOdometer)+' km';$('#vAvg').textContent=fmt(s.averageConsumption,1)+' L/100';$('#maintSpend').textContent=euro(s.maintenanceSpend);$('#maintCount').textContent=DB.maintenanceRecords.length;const rev=DB.maintenanceRecords.filter(x=>x.description.toLowerCase().includes('révision')).sort((a,b)=>b.date.localeCompare(a.date))[0];$('#lastService').textContent=rev?dateFR(rev.date):'—';
$('#fuelList').innerHTML=DB.fuelRecords.slice().sort((a,b)=>b.date.localeCompare(a.date)).slice(0,8).map(x=>`<div class="list-item"><div><b>${dateFR(x.date)}</b><small>${x.location||x.fuel||'Carburant'}</small></div><div class="right"><b>${fmt(x.liters,2)} L</b><small>${euro(x.totalPrice)}${x.consumption?' • '+fmt(x.consumption,1)+' L/100':''}</small></div></div>`).join('');
$('#maintList').innerHTML=DB.maintenanceRecords.slice().sort((a,b)=>b.date.localeCompare(a.date)).map(x=>`<div class="list-item"><div><b>${x.description}</b><small>${dateFR(x.date)}${x.location?' • '+x.location:''}</small></div><div class="right"><b>${x.cost?euro(x.cost):''}</b><small>${x.odometer?fmt(x.odometer)+' km':''}</small></div></div>`).join('')}
const settings=JSON.parse(localStorage.getItem('fc-settings')||'{}');if(settings.driverName)$('#driverName').value=settings.driverName;if(settings.navChoice)$('#navChoice').value=settings.navChoice;if(settings.lbcUrl)$('#lbcUrl').value=settings.lbcUrl;
$('#saveSettings').onclick=()=>{localStorage.setItem('fc-settings',JSON.stringify({driverName:$('#driverName').value,navChoice:$('#navChoice').value,lbcUrl:$('#lbcUrl').value}));toast('Réglages enregistrés')};
function openUrl(url,fallback){location.href=url;setTimeout(()=>{if(fallback)location.href=fallback},900)}
function action(a){const nav=$('#navChoice').value;const urls={lbc:$('#lbcUrl').value||'https://www.lbc.co.uk/radio/',music:'music://',podcasts:'podcasts://',spotify:'spotify://',youtube:'youtubemusic://'};if(a==='maps'){if(nav==='google')openUrl('comgooglemaps://','https://maps.google.com');else if(nav==='waze')openUrl('waze://','https://www.waze.com/live-map');else location.href='maps://';return}if(a==='lbc'){location.href=urls.lbc;return}openUrl(urls[a],a==='spotify'?'https://open.spotify.com':a==='youtube'?'https://music.youtube.com':null)}
$$('[data-action]').forEach(b=>b.onclick=()=>action(b.dataset.action));
$('#openDestination').onclick=()=>{const q=encodeURIComponent($('#destination').value.trim());if(!q)return toast('Saisissez une destination');const nav=$('#navChoice').value;if(nav==='google')location.href=`comgooglemaps://?q=${q}`;else if(nav==='waze')location.href=`https://waze.com/ul?q=${q}&navigate=yes`;else location.href=`maps://?q=${q}`};
function hav(a,b){const R=6371000,p=Math.PI/180,dlat=(b.latitude-a.latitude)*p,dlon=(b.longitude-a.longitude)*p;const x=Math.sin(dlat/2)**2+Math.cos(a.latitude*p)*Math.cos(b.latitude*p)*Math.sin(dlon/2)**2;return 2*R*Math.asin(Math.sqrt(x))}
function position(p){const c=p.coords,s=Math.max(0,(c.speed||0)*3.6);$('#gpsSpeed').textContent=Math.round(s);$('#tripSpeed').textContent=Math.round(s);$('#tripAltitude').textContent=c.altitude==null?'—':Math.round(c.altitude)+' m';if(tripStarted){if(lastPos){const d=hav(lastPos,c);if(d<250)tripMeters+=d}lastPos={latitude:c.latitude,longitude:c.longitude};tripSpeeds.push(s);$('#tripDistance').textContent=fmt(tripMeters/1000,2);$('#tripAvgSpeed').textContent=Math.round(tripSpeeds.reduce((a,b)=>a+b,0)/tripSpeeds.length||0)}}
if(navigator.geolocation)watchId=navigator.geolocation.watchPosition(position,()=>{}, {enableHighAccuracy:true,maximumAge:2000,timeout:10000});
setInterval(()=>{if(tripStarted){const sec=Math.floor((Date.now()-tripStarted)/1000);$('#tripDuration').textContent=String(Math.floor(sec/60)).padStart(2,'0')+':'+String(sec%60).padStart(2,'0')}},1000);
$('#tripToggle').onclick=()=>{if(!tripStarted){tripStarted=Date.now();tripMeters=0;tripSpeeds=[];lastPos=null;$('#tripToggle').textContent='Terminer le trajet';toast('Trajet démarré')}else{const record={date:new Date().toISOString(),distanceKm:tripMeters/1000,durationMs:Date.now()-tripStarted,avgSpeed:tripSpeeds.reduce((a,b)=>a+b,0)/(tripSpeeds.length||1)};const arr=JSON.parse(localStorage.getItem('fc-trips')||'[]');arr.unshift(record);localStorage.setItem('fc-trips',JSON.stringify(arr));tripStarted=null;$('#tripToggle').textContent='Démarrer le trajet';toast('Trajet enregistré sur cet iPhone')}};
$('#csvImport').onchange=async e=>{const f=e.target.files[0];if(!f)return;localStorage.setItem('fc-last-csv',await f.text());toast('Export Road Trip importé localement. Rechargez pour une future version de l’analyse.')};
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;$('#installBtn').classList.remove('hidden')});$('#installBtn').onclick=async()=>{if(installPrompt){installPrompt.prompt();installPrompt=null}else toast('Dans Safari : Partager → Sur l’écran d’accueil')};
if('serviceWorker' in navigator)navigator.serviceWorker.register('sw.js');load().catch(()=>toast('Impossible de charger les données Road Trip'));